import com.digidemic.unitof.UnitOf;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Types {
     Object converters[];
     List<String> namesList;
     List<List<String>> typesList;

     static String names[] = {
               "Acceleration",
               "Angle",
               "Area",
               "Data Storage",
               "Data Transfer Rate",
               "Electric Charge",
               "Force",
               "Frequency",
               "Fuel Economy",
               "Length",
               "Mass",
               "Metric Prefix",
               "Numeric Base",
               "Pressure",
               "Speed",
               "Temperature",
               "Time",
               "Torque",
               "Volume"
     };
     // Default Sorting based on the output value from low to high.
     static String types[][] = {
               // Acceleration
               {
                         "Microgalileos", "Milligalileos", "Galileos", "Gravity", "InchesPerMinutePerSecond",
                         "FeetPerHourPerSecond", "FeetPerMinutePerSecond", "KilometersPerHourPerSecond",
                         "KnotsPerSecond",
                         "InchesPerSecondSquared", "FeetPerSecondSquared", "YardsPerSecondSquared",
                         "MilesPerSecondSquared",
                         "MicrometersPerSecondSquared", "MillimetersPerSecondSquared", "NanometersPerSecondSquared",
                         "PicometersPerSecondSquared", "FemtometersPerSecondSquared", "AttometersPerSecondSquared",
                         "MilesPerHourPerSecond", "KilometersPerHourSquared", "KilometersPerSecondSquared",
                         "MetersPerSecondSquared", "DekametersPerSecondSquared", "HectometersPerSecondSquared",
                         "GigametersPerSecondSquared", "MegametersPerSecondSquared", "ExametersPerSecondSquared",
                         "PetametersPerSecondSquared"
               },
               // Angle
               {
                         "Circles", "Degrees", "Gradians", "Mils", "Minutes", "Quadrants", "Radians", "Revolutions",
                         "RightAngles", "Seconds", "Sextants", "Signs", "Turns"
               },
               // Area - Unsort
               { "Acres", "Ares", "Arpents", "Barns", "CircularInches", "CircularMils", "Hectares", "Homesteads",
                         "Roods", "Sabins", "SquareCentimeters", "SquareChains", "SquareDecimeters", "SquareDekameters",
                         "SquareFeet", "SquareHectometers", "SquareInches", "SquareKilometers", "SquareMeters",
                         "SquareMicrometers", "SquareMiles", "SquareMillimeters", "SquareNanometers", "SquarePerches",
                         "SquarePoles", "SquareRods", "SquareYards" },
               // Data Storage
               {
                         "Bits",
                         "Nibbles",
                         "Bytes",
                         "Words",
                         "Blocks",
                         "CDs_74Minutes",
                         "CDs_80Minutes",
                         "BluRay_SingleLayer",
                         "BluRay_DoubleLayer",
                         "DVDs_SingleSidedSingleLayer",
                         "DVDs_SingleSidedDoubleLayer",
                         "DVDs_DoubleSidedSingleLayer",
                         "DVDs_DoubleSidedDoubleLayer",
                         "FloppyDisks_35HD",
                         "FloppyDisks_35DD",
                         "FloppyDisks_525DD",
                         "FloppyDisks_525HD",
                         "SIUnitKilobits",
                         "SIUnitKilobytes",
                         "SIUnitMegabits",
                         "SIUnitMegabytes",
                         "SIUnitGigabits",
                         "SIUnitGigabytes",
                         "SIUnitTerabits",
                         "SIUnitTerabytes",
                         "SIUnitPetabits",
                         "SIUnitPetabytes",
                         "SIUnitExabits",
                         "SIUnitExabytes",
                         "SIUnitZettabits",
                         "SIUnitZettabytes",
                         "SIUnitYottabits",
                         "SIUnitYottabytes"
               },
               // Data Transfer Rate
               {
                         "BitsPerSecond",
                         "BytesPerSecond",
                         "EthernetsBase10",
                         "EthernetsBase100",
                         "EthernetsBase1000",
                         "FireWires400",
                         "FireWires800",
                         "FireWiresS1600_S3200",
                         "GigabitsPerSecond",
                         "GigabytesPerSecond",
                         "ISDNsDual",
                         "ISDNsSingle",
                         "KilobitsPerSecond",
                         "KilobytesPerSecond",
                         "MegabitsPerSecond",
                         "MegabytesPerSecond",
                         "Modems110b",
                         "Modems1200b",
                         "Modems14_4k",
                         "Modems2400b",
                         "Modems28_8k",
                         "Modems300b",
                         "Modems33_6k",
                         "Modems56k",
                         "Modems9600b",
                         "OCs1",
                         "OCs12",
                         "OCs192",
                         "OCs24",
                         "OCs3",
                         "OCs48",
                         "OCs768",
                         "PetabitsPerSecond",
                         "PetabytesPerSecond",
                         "SIUnitGigabitsPerSecond",
                         "SIUnitGigabytesPerSecond",
                         "SIUnitKilobitsPerSecond",
                         "SIUnitKilobytesPerSecond",
                         "SIUnitMegabitsPerSecond",
                         "SIUnitMegabytesPerSecond",
                         "SIUnitPetabitsPerSecond",
                         "SIUnitPetabytesPerSecond",
                         "SIUnitTerabitsPerSecond",
                         "SIUnitTerabytesPerSecond",
                         "TerabitsPerSecond",
                         "TerabytesPerSecond",
                         "USBs1_0",
                         "USBs2_0",
                         "USBs3_0",
                         "USBs3_1"
               },
               // Electric Charge
               {
                         "Abcoulombs",
                         "AmpereHours",
                         "AmpereMinutes",
                         "AmpereSeconds",
                         "Coulombs",
                         "EMUsOfCharge",
                         "ESUsOfCharge",
                         "ElectronCharge",
                         "FaradVolts",
                         "FaradayCarbon12",
                         "FaradayChemistry",
                         "FaradayPhysics",
                         "Franklins",
                         "Kilocoulombs",
                         "Megacoulombs",
                         "Microcoulombs",
                         "Millicoulombs",
                         "Nanocoulombs",
                         "Picocoulombs",
                         "Statcoulombs"
               },
               // Force - Unsort
               { "AtomicUnitsOfForce", "Attonewtons", "Centinewtons", "Decinewtons", "Dekanewtons", "Dynes",
                         "Exanewtons", "Femtonewtons", "Giganewtons", "GramForces", "GraveForces", "Hectonewtons",
                         "JouleCentimeters", "JouleMeters", "KilogramForces", "Kilonewtons", "Kiloponds",
                         "KilopoundForces", "LongTonForces", "Meganewtons", "MetricTonForces", "Micronewtons",
                         "MilligraveForces", "Millinewtons", "Nanonewtons", "Newtons", "OunceForces", "Petanewtons",
                         "Piconewtons", "Ponds", "PoundFeetPerSecondSquared", "PoundForces", "Poundals",
                         "ShortTonForces", "Sthenes", "Teranewtons" },

               // Frequency - Sorted
               {
                         "Attohertz",
                         "Centihertz",
                         "Decihertz",
                         "Dekahertz",
                         "Exahertz",
                         "Femtohertz",
                         "Gigahertz",
                         "Hectohertz",
                         "Hertz",
                         "Kilohertz",
                         "Megahertz",
                         "Microhertz",
                         "Millihertz",
                         "Nanohertz",
                         "Petahertz",
                         "Picohertz",
                         "RevolutionsPerDay",
                         "RevolutionsPerHour",
                         "RevolutionsPerMinute",
                         "RevolutionsPerSecond",
                         "Terahertz"
               },
               // Fuel Economy - Sorted
               {
                         "CentimetersPerLiter",
                         "DekametersPerLiter",
                         "ExametersPerLiter",
                         "GigametersPerLiter",
                         "HectometersPerLiter",
                         "KilometersPerGallonUK",
                         "KilometersPerGallonUS",
                         "KilometersPerLiter",
                         "MegametersPerLiter",
                         "MetersPerCubicCentimeter",
                         "MetersPerCubicFoot",
                         "MetersPerCubicInch",
                         "MetersPerCubicMeter",
                         "MetersPerCubicYard",
                         "MetersPerCupUK",
                         "MetersPerCupUS",
                         "MetersPerFluidOunceUK",
                         "MetersPerFluidOunceUS",
                         "MetersPerGallonUK",
                         "MetersPerGallonUS",
                         "MetersPerLiter",
                         "MetersPerPintUK",
                         "MetersPerPintUS",
                         "MetersPerQuartUK",
                         "MetersPerQuartUS",
                         "MilesPerGallonUK",
                         "MilesPerGallonUS",
                         "MilesPerLiterUS",
                         "NauticalMilesPerGallonUS",
                         "NauticalMilesPerLiter",
                         "PetametersPerLiter",
                         "TerametersPerLiter"
               },
               // Length - Sorted
               {
                         "Angstroms",
                         "Attometers",
                         "Barleycorns",
                         "Caliber",
                         "Centiinches",
                         "Centimeters",
                         "Chains",
                         "Cubits",
                         "Decimeters",
                         "Dekameters",
                         "Ells",
                         "Femtometers",
                         "Fingers",
                         "Hands",
                         "Inches",
                         "Links",
                         "Microinches",
                         "Micrometers",
                         "Microns",
                         "Millimeters",
                         "Nails",
                         "Nanometers",
                         "Perches",
                         "Picometers",
                         "Poles",
                         "ThousandthInches",
                         "Spans",
                         "Fathoms",
                         "Feet",
                         "Yardss",
                         "Rods",
                         "Ropes",
                         "Gigameters",
                         "Hectometers",
                         "Kilometers",
                         "Kiloyards",
                         "Leagues",
                         "Megameters",
                         "Meters",
                         "Miles",
                         "NauticalMilesInternational",
                         "NauticalMilesUK",
                         "NauticalMilesUSCustomary",
                         "Furlongs",
                         "LightYears",
                         "Exameters",
                         "Petameters",
                         "Terameters"
               },
               // Mass - Sorted
               {
                         "Attograms",
                         "Femtograms",
                         "Picograms",
                         "Nanograms",
                         "Micrograms",
                         "Milligrams",
                         "Centigrams",
                         "Decigrams",
                         "Grams",
                         "Decagrams",
                         "Hectograms",
                         "Kilograms",
                         "Carats",
                         "OuncesUS",
                         "OuncesMetric",
                         "Pounds",
                         "KilotonsMetric",
                         "Slugs",
                         "StonesUS",
                         "StonesUK",
                         "Quintals",
                         "Centners",
                         "TonsUS",
                         "TonsImperial",
                         "TonsMetric",
                         "Megagrams",
                         "Gigagrams",
                         "Teragrams",
                         "Petagrams",
                         "Exagrams",
                         "Gamma",
                         "Kilopounds"
               },
               // Metric Prefix - Sorted
               {
                         "Yocto",
                         "Zepto",
                         "Atto",
                         "Femto",
                         "Pico",
                         "Nano",
                         "Micro",
                         "Milli",
                         "Centi",
                         "Deci",
                         "NoPrefix",
                         "Deka",
                         "Hecto",
                         "Kilo",
                         "Mega",
                         "Giga",
                         "Tera",
                         "Peta",
                         "Exa",
                         "Zetta",
                         "Yotta"
               },
               // Numeric Base - Sorted
               {
                         "Binary",
                         "Base3",
                         "Base4",
                         "Base5",
                         "Base6",
                         "Base7",
                         "Base9",
                         "Base11",
                         "Base12",
                         "Base13",
                         "Base14",
                         "Base15",
                         "Base17",
                         "Base18",
                         "Base19",
                         "Base20",
                         "Base21",
                         "Base22",
                         "Base23",
                         "Base24",
                         "Base25",
                         "Base26",
                         "Base27",
                         "Base28",
                         "Base29",
                         "Base30",
                         "Base31",
                         "Base32",
                         "Base33",
                         "Base34",
                         "Base35",
                         "Base36",
                         "Decimal",
                         "Octal",
                         "Hexadecimal"
               },
               // Pressure - Sorted
               {
                         "Attopascals",
                         "Bars",
                         "Baryes",
                         "CentimetersOfMercury0C",
                         "CentimetersOfWater4C",
                         "Centipascals",
                         "Decibars",
                         "Decipascals",
                         "Dekapascals",
                         "DynesPerSquareCentimeter",
                         "Exapascals",
                         "FeetOfSeaWater",
                         "FeetOfWater4C",
                         "FeetOfWater60F",
                         "Femtopascals",
                         "Gigapascals",
                         "GramsPerSquareCentimeter",
                         "Hectopascals",
                         "InchesOfMercury32F",
                         "InchesOfMercury60F",
                         "InchesOfWater4C",
                         "InchesOfWater60F",
                         "KSI",
                         "KilogramsPerSquareCentimeter",
                         "KilogramsPerSquareMeter",
                         "KilogramsPerSquareMillimeter",
                         "KilonewtonsPerSquareMeter",
                         "Kilopascals",
                         "KipsPerSquareInch",
                         "LongTonsPerSquareFoot",
                         "LongTonsPerSquareInch",
                         "Megapascals",
                         "MetersOfSeaWater",
                         "MetersOfWater4C",
                         "Microbars",
                         "Micropascals",
                         "Millibars",
                         "MillimetersOfMercury0C",
                         "MillimetersOfWater4C",
                         "Millipascals",
                         "Nanopascals",
                         "NewtonsPerSquareCentimeter",
                         "NewtonsPerSquareMeter",
                         "NewtonsPerSquareMillimeter",
                         "PSI",
                         "Pascals",
                         "Petapascals",
                         "Picopascals",
                         "Pieze",
                         "PoundalsPerSquareFoot",
                         "PoundsPerSquareFoot",
                         "PoundsPerSquareInch",
                         "ShortTonsPerSquareFoot",
                         "ShortTonsPerSquareInch",
                         "StandardAtmospheres",
                         "SthenesPerSquareMeter",
                         "TechnicalAtmospheres",
                         "Terapascals",
                         "Torrs"
               },
               // Speed - Sorted
               {
                         "CentimetersPerHour",
                         "CentimetersPerMinute",
                         "CentimetersPerSecond",
                         "EarthsVelocity",
                         "FeetPerHour",
                         "FeetPerMinute",
                         "FeetPerSecond",
                         "FirstCosmicVelocity",
                         "InchesPerHour",
                         "InchesPerMinute",
                         "InchesPerSecond",
                         "KilometersPerHour",
                         "KilometersPerMinute",
                         "KilometersPerSecond",
                         "Knots",
                         "Light",
                         "Mach",
                         "MetersPerHour",
                         "MetersPerMinute",
                         "MetersPerSecond",
                         "MilesPerHour",
                         "MilesPerMinute",
                         "MilesPerSecond",
                         "MillimetersPerHour",
                         "MillimetersPerMinute",
                         "MillimetersPerSecond",
                         "SecondCosmicVelocity",
                         "SoundsInAir",
                         "SoundsInWater",
                         "ThirdCosmicVelocity",
                         "YardsPerHour",
                         "YardsPerMinute",
                         "YardsPerSecond"
               },
               // Temperature - Sorted
               { "Celsius", "Reaumur", "Fahrenheit", "Rankine", "Kelvin" },
               // Time - Sorted
               {
                         "Attoseconds",
                         "Femtoseconds",
                         "Picoseconds",
                         "Nanoseconds",
                         "Microseconds",
                         "Milliseconds",
                         "Seconds",
                         "Minutes",
                         "Hours",
                         "Days",
                         "Weeks",
                         "Fortnights",
                         "Months",
                         "Years",
                         "Decades",
                         "Centuries",
                         "Millenniums",
                         "JulianYears",
                         "LeapYears",
                         "GregorianYears"
               },
               // Torque - Sorted
               {
                         "DyneCentimeters",
                         "DyneMeters",
                         "DyneMillimeters",
                         "GramCentimeters",
                         "GramMeters",
                         "GramMillimeters",
                         "KilogramCentimeters",
                         "KilogramMeters",
                         "KilogramMillimeters",
                         "KilonewtonMeters",
                         "NewtonCentimeters",
                         "NewtonMeters",
                         "NewtonMillimeters",
                         "OunceFeet",
                         "OunceInches",
                         "PoundFeet",
                         "PoundInches"
               },
               // Volume - Sorted
               {
                         "Attoliters",
                         "Femtoliters",
                         "Picoliters",
                         "Nanoliters",
                         "Microliters",
                         "Milliliters",
                         "Centiliters",
                         "Deciliters",
                         "Liters",
                         "Decaliters",
                         "Hectoliters",
                         "Kiloliters",
                         "Megaliters",
                         "Gigaliters",
                         "Teraliters",
                         "Petaliters",
                         "Exaliters",
                         "AcreInches",
                         "AcreFeetUSSurvey",
                         "ArceFeet",
                         "CubicMillimeters",
                         "CubicCentimeters",
                         "CubicDecimeters",
                         "CubicMeters",
                         "CubicKilometers",
                         "CubicInches",
                         "CubicFeet",
                         "CubicYards",
                         "CubicMiles",
                         "BoardFeet",
                         "HundredCubicFeet",
                         "Cords",
                         "RegisterTons",
                         "BarrelsUK",
                         "BarrelsUS",
                         "GallonsUK",
                         "GallonsUS",
                         "QuartsUK",
                         "QuartsUS",
                         "PintsUK",
                         "PintsUS",
                         "CupsUK",
                         "CupsUS",
                         "FluidOuncesUK",
                         "FluidOuncesUS",
                         "GillsUK",
                         "GillsUS",
                         "MinimsUK",
                         "MinimsUS",
                         "Drops",
                         "TeaspoonsUK",
                         "TeaspoonsUS",
                         "TablespoonsUK",
                         "TablespoonsUS",
                         "DessertspoonsUK",
                         "DessertspoonsUS",
                         "BarrelsOfOil",
                         "Tuns",
                         "Hogsheads",
                         "Steres",
                         "Decisteres"
               }
     };

     Types() {
          converters = new Object[] {
                    new UnitOf.Acceleration(),
                    new UnitOf.Angle(),
                    new UnitOf.Area(),
                    new UnitOf.DataStorage(),
                    new UnitOf.DataTransferRate(),
                    new UnitOf.ElectricCharge(),
                    new UnitOf.Force(),
                    new UnitOf.Frequency(),
                    new UnitOf.FuelEconomy(),
                    new UnitOf.Length(),
                    new UnitOf.Mass(),
                    new UnitOf.MetricPrefix(),
                    new UnitOf.NumericBase(),
                    new UnitOf.Pressure(),
                    new UnitOf.Speed(),
                    new UnitOf.Temperature(),
                    new UnitOf.Time(),
                    new UnitOf.Torque(),
                    new UnitOf.Volume()
          };
          namesList = Arrays.asList(names);
          typesList = new ArrayList<>();
          for (int i = 0; i < types.length; i++) {
               List<String> _aTemp = Arrays.asList(types[i]);
               typesList.add(_aTemp);
          }
     }
}
